spring:
  datasource:
#    url: "jdbc:h2:./db/project-manager"
#    username: "sa"
#    password: ""
    url: "jdbc:postgresql://localhost/postgres"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

